//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo_CS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correlativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Correlativo()
        {
            this.Emergencias = new HashSet<Emergencias>();
            this.EmpleadosXCorrelativo = new HashSet<EmpleadosXCorrelativo>();
            this.PacientesXCorrelativo = new HashSet<PacientesXCorrelativo>();
            this.UnidadesXCorrelativo = new HashSet<UnidadesXCorrelativo>();
            this.VehiculosXCorrelativo = new HashSet<VehiculosXCorrelativo>();
        }
    
        public int Correlativo1 { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tipo { get; set; }
    
        public virtual AccidentesDeTransito AccidentesDeTransito { get; set; }
        public virtual Cirugias Cirugias { get; set; }
        public virtual TipoCorrelativo TipoCorrelativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergencias> Emergencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadosXCorrelativo> EmpleadosXCorrelativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacientesXCorrelativo> PacientesXCorrelativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadesXCorrelativo> UnidadesXCorrelativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculosXCorrelativo> VehiculosXCorrelativo { get; set; }
    }
}
