//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo_CS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.EmpleadosXCorrelativo = new HashSet<EmpleadosXCorrelativo>();
        }
    
        public string CodigoEmpleado { get; set; }
        public string PrimerNombreEmpleado { get; set; }
        public string SegundoNombreEmpleado { get; set; }
        public string PrimerApellidoEmpleado { get; set; }
        public string SegundoApellidoEmpleado { get; set; }
        public int Genero { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int TipoEmpleado { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadosXCorrelativo> EmpleadosXCorrelativo { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual TipoEmpleado TipoEmpleado1 { get; set; }
    }
}
