//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo_CS.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComandosSalvamentoEntities : DbContext
    {
        public ComandosSalvamentoEntities()
            : base("name=ComandosSalvamentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaIncidentes> CategoriaIncidentes { get; set; }
        public virtual DbSet<Correlativo> Correlativo { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<EmpleadosXCorrelativo> EmpleadosXCorrelativo { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<HospitalesSS> HospitalesSS { get; set; }
        public virtual DbSet<Incidentes> Incidentes { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<TipoCorrelativo> TipoCorrelativo { get; set; }
        public virtual DbSet<TipoEmpleado> TipoEmpleado { get; set; }
        public virtual DbSet<TipoLlamada> TipoLlamada { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<UnidadesXCorrelativo> UnidadesXCorrelativo { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
        public virtual DbSet<VehiculosXCorrelativo> VehiculosXCorrelativo { get; set; }
        public virtual DbSet<AccidentesDeTransito> AccidentesDeTransito { get; set; }
        public virtual DbSet<Cirugias> Cirugias { get; set; }
        public virtual DbSet<Emergencias> Emergencias { get; set; }
        public virtual DbSet<PacientesXCorrelativo> PacientesXCorrelativo { get; set; }
    }
}
