//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo_CS.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientesXCorrelativo
    {
        public int CodCorrelativo { get; set; }
        public string CodPaciente { get; set; }
        public Nullable<int> FrecuenciaCardiaca { get; set; }
        public Nullable<int> FrecuenciaRespiratoria { get; set; }
        public Nullable<int> PresionArterial { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public Nullable<double> SaturacionOxigeno { get; set; }
        public string CodHospital { get; set; }
        public string Telefono { get; set; }
        public string NombreAcompañante { get; set; }
        public string Parentesco { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<System.TimeSpan> HoraLlegada { get; set; }
    
        public virtual Correlativo Correlativo { get; set; }
        public virtual HospitalesSS HospitalesSS { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
